machine:
  time:
    servers:
      - 192.168.130.1
  network:
    interfaces:
      - interface: ens3
        dhcp: false
        addresses:
          - 192.168.130.12/24
        routes:
          - network: 0.0.0.0/0
            gateway: 192.168.130.1
    nameservers:
      - 192.168.130.1
      - 1.1.1.1
---
apiVersion: v1alpha1
kind: HostnameConfig
auto:
  $patch: delete
hostname: iots-lab-worker-1
